### ISSUE TITLE
请问电位器型号（？

### ISSUE THREAD

**Issue by nerimoe** [GEEKiDoS/ongeki-io#1]
rt, 想造手台但是使用现有的电位器无法工作，所以厚着脸皮来问一下（）

**Comment by GEEKiDoS** [comment]
你自己看一下输出的值范围
然后自己写个函数映射到[int16min, int16max]就行
用不着买一样的 我写这个东西的时候买的电位器也不行

**Comment by nerimoe** [comment]
收到（
